project:
  type: website

website:
  title: "Epiverse-CONNECT map"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: dependency_map.qmd
        text: Organize by dependencies
      - href: dependency_network.qmd
        text: Connect by dependencies
      - href: coauthors_map.qmd
        text: Organize by authors
      - href: embeddings_map.qmd
        text: Organize by topics

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



